name: Update readme

on:
  schedule:
    # At 14:53 on the first day the month
    # Semi-random time to prevent high loads of GitHub Actions workflow runs
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: node ./main.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push readme changes
        run: |
          git config --global user.email "talk@selwyn.cc"
          git config --global user.name "Selwyn"
          git add .
          git commit --message 'Update readme'
          git push --force
