name: Update readme

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: node ./main.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push readme changes
        run: |
          git config --global user.email "talk@selwyn.cc"
          git config --global user.name "Selwyn"
          git add .
          git commit --amend --message 'Update readme'
          git push --force
